import dotenv from "dotenv"; dotenv.config();
import express from "express";
import cors from "cors";
import { getDb } from "./db/init";
import { getAgentManager } from "./agents/manager";
import authRoutes from "./routes/auth";
import adminRoutes from "./routes/admin";
import customerRoutes from "./routes/customer";
import provisionRoutes from "./routes/provision";
import healthRoutes from "./routes/health";
const app = express();
const PORT = parseInt(process.env.PORT || "4000", 10);
app.use(cors({ origin: process.env.FRONTEND_URL || "http://localhost:3000", credentials: true }));
app.use(express.json());
app.use("/api/auth", authRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/customer", customerRoutes);
app.use("/api/provision", provisionRoutes);
app.use("/api/health", healthRoutes);
app.get("/", (_req, res) => res.json({ name: "DeskAgents Runtime Server", version: "1.0.0" }));
getDb();
const server = app.listen(PORT, () => console.log("DeskAgents Server on http://localhost:" + PORT));
async function shutdown(s: string) { await getAgentManager().shutdown(); server.close(() => process.exit(0)); }
process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));
export default app;
